<?php
namespace System\Database\Schema;

use System\Database\DB;
use System\Database\Schema\Definitions\ColumnDefinition;
use System\Database\Schema\Definitions\IndexDefinition;
use System\Database\Schema\Definitions\ForeignKeyDefinition;

/**
 * PgsqlSchema
 *
 * Purpose:
 *   Compile TableBlueprint into PostgreSQL SQL statements.
 *
 * Notes:
 *   - Identity columns for increments/bigIncrements (GENERATED BY DEFAULT AS IDENTITY).
 *   - ENUM is emulated via CHECK by default (portable). You can pre-create TYPE if needed (not automated here).
 *   - Partial indexes supported via IndexDefinition->where().
 *   - Include columns (covering indexes) supported via IndexDefinition->include().
 *   - Collation per column is rarely used; charset/collation options are ignored at table level.
 *   - "SET" type is not supported; emulate with TEXT + CHECK if needed.
 */
final class PgsqlSchema extends BaseSchema
{
    /* ===================== Public (introspection) ===================== */

    /** Check if table exists (current_schema search_path). */
    public function existsTable($table)
    {
        $row = DB::select(
            "SELECT COUNT(*) AS c
             FROM information_schema.tables
             WHERE table_schema = ANY (current_schemas(true)) AND table_name = ?",
            array($table),
            $this->connection
        );
        return isset($row[0]['c']) ? ((int)$row[0]['c'] > 0) : false;
    }

    /** Check if column exists. */
    public function existsColumn($table, $column)
    {
        $row = DB::select(
            "SELECT COUNT(*) AS c
             FROM information_schema.columns
             WHERE table_schema = ANY (current_schemas(true)) AND table_name = ? AND column_name = ?",
            array($table, $column),
            $this->connection
        );
        return isset($row[0]['c']) ? ((int)$row[0]['c'] > 0) : false;
    }

    /** Normalized columns metadata. */
    public function columns($table)
    {
        $rows = DB::select(
            "SELECT column_name, data_type, is_nullable, column_default
             FROM information_schema.columns
             WHERE table_schema = ANY (current_schemas(true)) AND table_name = ?
             ORDER BY ordinal_position",
            array($table),
            $this->connection
        );
        $out = array();
        foreach ($rows as $r) {
            $auto = false;
            if (isset($r['column_default']) && is_string($r['column_default'])) {
                $d = strtolower($r['column_default']);
                // identity or sequence default:
                $auto = (strpos($d, 'nextval(') !== false) || (strpos($d, 'generated') !== false);
            }
            $out[] = array(
                'name'           => $r['column_name'],
                'type'           => strtolower($r['data_type']),
                'nullable'       => strtoupper($r['is_nullable']) === 'YES',
                'default'        => $r['column_default'],
                'auto_increment' => $auto,
                'comment'        => null, // add pg_catalog.col_description if needed
            );
        }
        return $out;
    }

    /* ===================== Compilation ===================== */

    protected function compileCreateTable(TableBlueprint $bp)
    {
        $table = $bp->table();
        $defs  = array();

        foreach ($bp->allColumns() as $c) {
            $defs[] = $this->compileColumn($c);
        }

        // Inline PK/UNIQUE only (others via CREATE INDEX after)
        $inline = $this->compileInlineIndexes($bp->allIndexes());
        $defs   = array_merge($defs, $inline);

        // FK inline
        foreach ($bp->allForeigns() as $fk) {
            $defs[] = $this->compileForeignInline($fk);
        }

        // Check constraints
        foreach ($bp->checkConstraints() as $check) {
            $defs[] = 'CHECK ('.$check.')';
        }

        $sql = 'CREATE TABLE '.$this->qi($table).' ('.implode(', ', $defs).')';

        // Table options: ignore engine/charset/collate; comment available
        $post = array($sql);
        $opts = $bp->options();
        if (!empty($opts['comment'])) {
            $post[] = 'COMMENT ON TABLE '.$this->qi($table).' IS '.$this->literal($opts['comment']);
        }

        // Post indexes
        $post = array_merge($post, $this->compilePostCreateIndexes($table, $bp->allIndexes()));

        return $post;
    }

    protected function compileAlterTable(TableBlueprint $bp)
    {
        $table = $bp->table();
        $sqls  = array();

        // ADD COLUMNS
        foreach ($bp->alterAddColumns() as $c) {
            $sqls[] = 'ALTER TABLE '.$this->qi($table).' ADD COLUMN '.$this->compileColumn($c, false);
        }

        // MODIFY COLUMNS (Postgres: ALTER COLUMN ... TYPE/SET NOT NULL/SET DEFAULT)
        foreach ($bp->alterModifyColumns() as $c) {
            // In a portable way we re-specify type + nullability + default (3 statements safest)
            $map = $this->mapType($c);
            $sqls[] = 'ALTER TABLE '.$this->qi($table).' ALTER COLUMN '.$this->qi($c->name).' TYPE '.$map;

            if ($c->nullable) {
                $sqls[] = 'ALTER TABLE '.$this->qi($table).' ALTER COLUMN '.$this->qi($c->name).' DROP NOT NULL';
            } else {
                $sqls[] = 'ALTER TABLE '.$this->qi($table).' ALTER COLUMN '.$this->qi($c->name).' SET NOT NULL';
            }

            if ($c->default_raw !== null) {
                $sqls[] = 'ALTER TABLE '.$this->qi($table).' ALTER COLUMN '.$this->qi($c->name).' SET DEFAULT '.$c->default_raw;
            } elseif ($c->default !== null) {
                $sqls[] = 'ALTER TABLE '.$this->qi($table).' ALTER COLUMN '.$this->qi($c->name).' SET DEFAULT '.$this->literal($c->default);
            } else {
                $sqls[] = 'ALTER TABLE '.$this->qi($table).' ALTER COLUMN '.$this->qi($c->name).' DROP DEFAULT';
            }
        }

        // DROP COLUMNS
        foreach ($bp->alterDropColumns() as $name) {
            $sqls[] = 'ALTER TABLE '.$this->qi($table).' DROP COLUMN '.$this->qi($name);
        }

        // ADD INDEXES
        foreach ($bp->alterAddIndexes() as $idx) {
            $sqls[] = $this->compileCreateIndex($table, $idx);
        }

        // DROP INDEXES
        foreach ($bp->alterDropIndexes() as $name) {
            // Primary key drop:
            if (strtolower($name) === 'primary' || preg_match('/_pk$/i', $name)) {
                $sqls[] = 'ALTER TABLE '.$this->qi($table).' DROP CONSTRAINT '.$this->qi($table.'_pkey');
            } else {
                $sqls[] = 'DROP INDEX IF EXISTS '.$this->qi($name);
            }
        }

        // ADD FOREIGN KEYS
        foreach ($bp->alterAddForeigns() as $fk) {
            $sqls[] = 'ALTER TABLE '.$this->qi($table).' ADD '.$this->compileForeignInline($fk);
        }

        // DROP FOREIGN KEYS
        foreach ($bp->alterDropForeigns() as $name) {
            $sqls[] = 'ALTER TABLE '.$this->qi($table).' DROP CONSTRAINT '.$this->qi($name);
        }

        // RENAME COLUMNS
        foreach ($bp->renameColumns() as $rename) {
            $sqls[] = 'ALTER TABLE '.$this->qi($table).' RENAME COLUMN '.$this->qi($rename['from']).' TO '.$this->qi($rename['to']);
        }

        // ADD CHECK CONSTRAINTS
        foreach ($bp->checkConstraints() as $check) {
            $sqls[] = 'ALTER TABLE '.$this->qi($table).' ADD CHECK ('.$check.')';
        }

        return $sqls;
    }

    protected function compileRenameTable($from, $to)
    {
        return array('ALTER TABLE '.$this->qi($from).' RENAME TO '.$this->qi($to));
    }

    protected function compileRenameColumn($table, $from, $to)
    {
        return array('ALTER TABLE '.$this->qi($table).' RENAME COLUMN '.$this->qi($from).' TO '.$this->qi($to));
    }

    protected function compileDropTable($table, $ifExists)
    {
        return array('DROP TABLE '.($ifExists?'IF EXISTS ':'').$this->qi($table).' CASCADE');
    }

    /* ===================== Helpers ===================== */

    /** Compile ColumnDefinition into PG fragment. */
    private function compileColumn(ColumnDefinition $c, $forCreate = true)
    {
        $name = $this->qi($c->name);
        $type = $this->mapType($c);

        $sql = $name.' '.$type;

        // identity for auto-increment (already baked into mapType for increments)
        if (!$this->isIdentityType($c)) {
            if ($c->default_raw !== null) {
                $sql .= ' DEFAULT '.$c->default_raw;
            } elseif ($c->default !== null) {
                $sql .= ' DEFAULT '.$this->literal($c->default);
            }
        }

        $sql .= $c->nullable ? '' : ' NOT NULL';

        // check
        if ($c->check) {
            $sql .= ' CHECK ('.$c->check.')';
        }

        // comment
        if ($forCreate && $c->comment) {
            // emit in post phase by caller if needed; here we just return the column fragment
        }

        return $sql;
    }

    /** Whether type already includes identity (increments/bigIncrements). */
    private function isIdentityType(ColumnDefinition $c)
    {
        return ($c->type === 'increments' || $c->type === 'bigIncrements');
    }

    /** Map portable type to PG type. */
    private function mapType(ColumnDefinition $c)
    {
        switch ($c->type) {
            case 'increments':
                // Standardized identity (more future-proof than serial)
                return 'INTEGER GENERATED BY DEFAULT AS IDENTITY';
            case 'bigIncrements':
                return 'BIGINT GENERATED BY DEFAULT AS IDENTITY';
            case 'int':
                return 'INTEGER';
            case 'bigint':
                return 'BIGINT';
            case 'tinyint':
                return 'SMALLINT';
            case 'bool':
                return 'BOOLEAN';
            case 'string':
                $len = $c->length !== null ? max(1,(int)$c->length) : 255;
                return 'VARCHAR('.$len.')';
            case 'text':
            case 'mediumtext':
            case 'longtext':
                return 'TEXT';
            case 'json':
                return 'JSONB';
            case 'decimal':
                $p = $c->precision !== null ? max(1,(int)$c->precision) : 10;
                $s = $c->scale     !== null ? max(0,(int)$c->scale)     : 0;
                return 'DECIMAL('.$p.','.$s.')';
            case 'float':
                return 'REAL';
            case 'double':
                return 'DOUBLE PRECISION';
            case 'date':
                return 'DATE';
            case 'datetime':
                return 'TIMESTAMP(0) WITHOUT TIME ZONE';
            case 'timestamp':
                return 'TIMESTAMP(0) WITHOUT TIME ZONE';
            case 'time':
                return 'TIME(0) WITHOUT TIME ZONE';
            case 'year':
                // emulate via smallint with CHECK 1900..2155 for example
                return 'SMALLINT';
            case 'enum':
                // emulate: TEXT + CHECK (val in (...))
                $vals = $c->enum_values ? array_map(array($this,'literal'), $c->enum_values) : array("'0'");
                return 'TEXT CHECK ('.$this->qi($c->name).' IN ('.implode(',', $vals).'))';
            case 'set':
                // no native SET; store TEXT
                return 'TEXT';
            case 'point':
                return 'POINT';
            case 'blob':
                return 'BYTEA';
            default:
                return 'TEXT';
        }
    }

    /** Inline PK/UNIQUE constraints for CREATE TABLE. */
    private function compileInlineIndexes(array $indexes)
    {
        $out = array();
        foreach ($indexes as $idx) {
            $t = strtolower($idx->type);
            if ($t === 'primary') {
                $out[] = 'PRIMARY KEY ('.$this->qcols($idx->columns).')';
            } elseif ($t === 'unique') {
                $nm = $idx->name ?: 'uk_'.implode('_',$idx->columns);
                $out[] = 'CONSTRAINT '.$this->qi($nm).' UNIQUE ('.$this->qcols($idx->columns).')';
            }
        }
        return $out;
    }

    /** Post CREATE INDEX (supports where/include/using). */
    private function compilePostCreateIndexes($table, array $indexes)
    {
        $out = array();
        foreach ($indexes as $idx) {
            $t = strtolower($idx->type);
            if ($t === 'index' || $t === 'unique' || $t === 'fulltext' /* map to GIN? */) {
                $out[] = $this->compileCreateIndex($table, $idx);
            } else if ($t === 'spatial') {
                // PG: spatial indexes require PostGIS (GIST on geometry). Here fallback to GIST if requested.
                $idx->using = $idx->using ?: 'gist';
                $out[] = $this->compileCreateIndex($table, $idx);
            }
        }
        return $out;
    }

    /** CREATE INDEX statement. */
    private function compileCreateIndex($table, IndexDefinition $idx)
    {
        $t = strtolower($idx->type);
        $name = $this->qi($idx->name ?: $table.'_'.implode('_',$idx->columns).'_'.$t);

        $unique = ($t === 'unique') ? 'UNIQUE ' : '';
        $using  = $idx->using ? ' USING '.strtoupper($idx->using) : '';

        // Fulltext: best-effort -> GIN on to_tsvector of first column
        $colsSql = $this->qcols($idx->columns);
        if ($t === 'fulltext') {
            $expr = "to_tsvector('simple', ".implode(" || ' ' || ", array_map(function($c){ return $this->qi($c); }, $idx->columns)).')';
            $colsSql = '('.$expr.')';
            $using   = ' USING GIN';
        }

        $sql = 'CREATE '.$unique.'INDEX '.$name.' ON '.$this->qi($table).$using.' ('.$colsSql.')';

        if ($idx->include && !empty($idx->include)) {
            // covering indexes in PG 11+: INCLUDE (...)
            $sql .= ' INCLUDE ('.$this->qcols($idx->include).')';
        }
        if ($idx->where) {
            $sql .= ' WHERE '.$idx->where;
        }

        return $sql;
    }

    /** Compile FK (constraint ...) */
    private function compileForeignInline(ForeignKeyDefinition $fk)
    {
        $name = $fk->name !== '' ? ' CONSTRAINT '.$this->qi($fk->name) : '';
        $sql  = $name.' FOREIGN KEY ('.$this->qcols($fk->columns).') REFERENCES '.$this->qi($fk->ref_table)
              .' ('.$this->qcols($fk->ref_columns).')';

        if ($fk->on_delete) $sql .= ' ON DELETE '.strtoupper($this->fkAction($fk->on_delete));
        if ($fk->on_update) $sql .= ' ON UPDATE '.strtoupper($this->fkAction($fk->on_update));

        if ($fk->deferrable) $sql .= ' DEFERRABLE';
        if ($fk->initially_deferred) $sql .= ' INITIALLY DEFERRED';

        return $sql;
    }

    private function fkAction($a)
    {
        $a = strtolower(trim((string)$a));
        switch ($a) {
            case 'cascade':     return 'cascade';
            case 'restrict':    return 'restrict';
            case 'set null':    return 'set null';
            case 'no action':   return 'no action';
            case 'set default': return 'set default';
            default:            return 'no action';
        }
    }

    /** 
     * SQL literal for PostgreSQL.
     * Handles special PostgreSQL keywords and expressions that should NOT be quoted.
     */
    private function literal($v)
    {
        if ($v === null) return 'NULL';
        if (is_bool($v)) return $v ? 'TRUE' : 'FALSE';
        if (is_int($v) || is_float($v)) return (string)$v;
        
        // Check if it's a special keyword/expression that should NOT be quoted
        if (is_string($v)) {
            $upper = strtoupper(trim($v));
            
            // 1. NULL keyword
            if ($upper === 'NULL') {
                return 'NULL';
            }
            
            // 2. Boolean literals (PostgreSQL native)
            if ($upper === 'TRUE' || $upper === 'FALSE') {
                return $upper;
            }
            
            // 3. CURRENT_TIMESTAMP and variants (with optional precision)
            if ($upper === 'CURRENT_TIMESTAMP' || preg_match('/^CURRENT_TIMESTAMP\(\d+\)$/', $upper)) {
                return $upper;
            }
            
            // 4. Other PostgreSQL time functions (no parentheses needed for defaults)
            $timeFunctions = [
                'NOW', 'CURRENT_DATE', 'CURRENT_TIME', 'LOCALTIME', 'LOCALTIMESTAMP',
                'TRANSACTION_TIMESTAMP', 'STATEMENT_TIMESTAMP', 'CLOCK_TIMESTAMP',
            ];
            if (in_array($upper, $timeFunctions, true)) {
                return $upper;
            }
            
            // 5. Expression defaults - wrapped in parentheses (PostgreSQL)
            // Pattern: (FUNCTION_NAME(...)) or (expression)
            if (preg_match('/^\(.+\)$/', $v)) {
                // It's already wrapped in parentheses, check if it's a valid expression
                $inner = strtoupper(trim(substr($v, 1, -1)));
                
                // Common functions that are valid in expression defaults
                $validFunctions = [
                    'NOW', 'CURRENT_DATE', 'CURRENT_TIME', 'LOCALTIME', 'LOCALTIMESTAMP',
                    'GEN_RANDOM_UUID', 'UUID_GENERATE_V4', 'MD5', 'RANDOM',
                    'JSON_BUILD_OBJECT', 'JSON_BUILD_ARRAY', 'EXTRACT', 'AGE',
                ];
                
                foreach ($validFunctions as $func) {
                    if (strpos($inner, $func) === 0) {
                        return $v; // Return as-is (no quotes)
                    }
                }
                
                // Check for common patterns like (1+1), (column_name), etc.
                if (preg_match('/^[\w\s\+\-\*\/\(\)]+$/', $inner)) {
                    return $v; // Return as-is (no quotes)
                }
            }
        }
        
        // Default: quote the string
        return "'".str_replace("'", "''", (string)$v)."'";
    }

    /* ===================== New Methods ===================== */

    /**
     * Compile DUPLICATE TABLE for PostgreSQL.
     * Uses: CREATE TABLE new (LIKE old INCLUDING ALL) + INSERT INTO new SELECT * FROM old
     */
    protected function compileDuplicateTable($originalTable, $newTable, $withData)
    {
        $createSql = 'CREATE TABLE '.$this->qi($newTable).' (LIKE '.$this->qi($originalTable).' INCLUDING ALL)';
        
        if ($withData) {
            $insertSql = 'INSERT INTO '.$this->qi($newTable).' SELECT * FROM '.$this->qi($originalTable);
            return array($createSql, $insertSql);
        }
        
        return array($createSql);
    }

    /**
     * Compile DESCRIBE TABLE for PostgreSQL.
     */
    protected function compileDescribeTable($table)
    {
        $sql = "SELECT 
                    column_name, 
                    data_type, 
                    is_nullable, 
                    column_default,
                    character_maximum_length,
                    numeric_precision,
                    numeric_scale
                FROM information_schema.columns 
                WHERE table_name = ? 
                ORDER BY ordinal_position";
        
        return DB::select($sql, array($table), $this->connection);
    }

    /**
     * Compile TRUNCATE TABLE for PostgreSQL.
     */
    protected function compileTruncateTable($table)
    {
        return array('TRUNCATE TABLE '.$this->qi($table));
    }

    /**
     * Compile LIST TABLES for PostgreSQL.
     */
    protected function compileListTables($pattern)
    {
        $sql = "SELECT table_name 
                FROM information_schema.tables 
                WHERE table_schema = 'public'";
        $params = array();
        
        if ($pattern !== null) {
            $sql .= " AND table_name LIKE ?";
            $params[] = $pattern;
        }
        
        $rows = DB::select($sql, $params, $this->connection);
        
        // Extract table names from result
        $tables = array();
        foreach ($rows as $row) {
            $tables[] = $row['table_name'];
        }
        
        return $tables;
    }
}
