<?php
// Check if PATH_ROOT is not defined, prevent direct access
if (!defined('PATH_ROOT')) {
    exit('No direct access allowed.');
}

/**
 * User Roles Configuration
 * Generated by CMSFullForm Installer
 */

return [
    'admin' => [
        'name' => 'Administrator',
        'description' => 'Full access to all features and settings',
        'permissions' => [
            'Backend\Home' => [
                'index',
            ],
            'Backend\Files' => [
                'index',
                'add',
                'edit',
                'delete',
                'manage',
                'timeline'
            ],
            'Backend\Posts' => [
                'index',
                'edit',
                'add',
                'delete',
                'clone',
                'import',
                'export',
                'bulkedit',
                'getbulkposts',
                'createbulkpost',
                'updatebulkpost',
                'changestatus',
                'manage',
            ],
            'Backend\Terms' => [
                'index',
                'add',
                'edit',
                'delete',
                'changestatus'
            ],
            'Backend\Users' => [
                'index',
                'edit',
                'add',
                'delete',
                'changestatus',
                'update_status',
            ],
            'Backend\Options' => [
                'index',
                'lists',
                'add',
                'edit',
                'delete',
            ],
            'Backend\Languages' => [
                'index',
                'add',
                'edit',
                'setdefault',
                'changestatus',
                'delete',
                'manage'
            ],
            'Backend\Libraries' => [
                'themes',
                'plugins',
                'action',
                'upload',
                'uploadWithOverwrite',
                'manage'
            ],
            'Backend\Backups' => [
                'index',
                'settings',
                'create',
                'delete',
                'download',
                'restore',
                'manage'
            ],
            'Backend\Settings' => [
                'index',
                'general',
                'media',
                'performance',
                'seo',
                'social_api',
                'email',
                'security',
                'developer',
                'manage'
            ],
        ],
        'is_active' => true,
        'created_at' => '2025-09-04 06:21:49',
    ],
    'moderator' => [
        'name' => 'Moderator',
        'description' => 'Manage content and moderate users',
        'permissions' => [
            'Backend\Home' => [
                'index',
            ],
            'Backend\Files' => [
                'index',
                'add',
                'edit',
                'delete',
                'manage',
                'timeline'
            ],
            'Backend\Posts' => [
                'index',
                'edit',
                'add',
                'delete',
                'clone',
                'import',
                'bulkedit',
                'getbulkposts',
                'createbulkpost',
                'updatebulkpost',
                'changestatus',
                'manage',
            ],
            'Backend\Terms' => [
                'index',
                'add',
                'edit',
                'delete',
                'changestatus'
            ],
        ],
        'is_active' => true,
        'created_at' => '2025-09-04 06:21:49',
    ],
    'author' => [
        'name' => 'Author',
        'description' => 'Create and manage own content',
        'permissions' => [
            'Backend\Home' => [
                'index',
            ],
            'Backend\Files' => [
                'index',
                'add',
                'edit',
                'delete',
                'timeline'
            ],
            'Backend\Posts' => [
                'index',
                'edit',
                'add',
                'delete',
                'clone',
                'bulkedit',
                'getbulkposts',
                'createbulkpost',
                'updatebulkpost',
                'changestatus'
            ],
            'Backend\Terms' => [
                'index',
                'add'
            ],
        ],
        'is_active' => true,
        'created_at' => '2025-09-04 06:21:49',
    ],
    'contributor' => [
        'name' => 'Contributor',
        'description' => 'Contribute to the content',
        'permissions' => [
            'Backend\Home' => [
                'index',
            ],
            'Backend\Files' => [
                'index',
                'add',
                'edit',
                'timeline'
            ],
            'Backend\Posts' => [
                'index',
                'edit',
                'add'
            ],
            'Backend\Terms' => [
                'index'
            ],
        ],
        'is_active' => true,
        'created_at' => '2025-09-04 06:21:49',
    ],
    'member' => [
        'name' => 'Member',
        'description' => 'Basic access to view content',
        'permissions' => [
            
        ],
        'is_active' => true,
        'created_at' => '2025-09-04 06:21:49',
    ]
];
